### ISSUE TITLE
False calculation for Zodiac (Animal) and Sequence 10 cycle (Sak)

### ISSUE THREAD

**Issue by Sovichetra** [seanghay/khmercal#1]
I try this

> khmercal "2023-04-05T19:33:00+07:00"

    Day: 1R (16 of 29)
    Month: CHÉTR
    Years: 2566 B.E, 1383 J.E, 2023 C.E
    Days: 384 days
    Animal: KARL
    Sequence: IV ចត្វាស័ក
answer it's look fine then I try this

> khmercal "2023-04-17T00:30:00+07:00"

    Day: 12R (27 of 29)
    Month: CHÉTR
    Years: 2566 B.E, 1383 J.E, 2023 C.E
    Days: 384 days
    Animal: KARL
    Sequence: IV ចត្វាស័ក
    
After Khmer new year the Zodiac (Animal) should change to `"THOS"` and Sequence (SAK) should be `'V បញ្ចស័ក'` full answer should like this:

> khmercal  "2023-04-17T00:30:00+07:00"

    Day: 12R (27 of 29)
    Month: CHÉTR
    Years: 2566 B.E, 1383 J.E, 2023 C.E
    Days: 384 days
    Animal: THOS
    Sequence: V បញ្ចស័ក
At first I think maybe It's wrong cuz it's wait to change when B.E year increase at Pisak Bochea but It's not.
I tried this the day after `VĬSAKH` and this what I got

> khmercal "2023-05-06T00:30:00+07:00"

    Day: 2R (17 of 30)
    Month: VĬSAKH
    Years: 2567 B.E, 1383 J.E, 2023 C.E
    Days: 384 days
    Animal: KARL
    Sequence: IV ចត្វាស័ក
B.E year increased but Animal and Sequence remind the same

**Comment by seanghay** [comment]
Thanks for reporting the bug. I've just released an new minor version `0.1.0` for the fix. You can try it if it works correctly.

**Comment by Sovichetra** [comment]
> 

I found one more strange
I run CLI at 5PM Local Time :

> khmercal "2023-05-05T17:58:01+07:00"

    Day: 1R (16 of 30)
    Month: VĬSAKH
    Years: 2567 B.E, 1384 J.E, 2023 C.E
    Days: 384 days
    Zodiac: THOS
    Sequence: V បញ្ចស័ក

it's look fine but after 7PM it's showing next day:

> khmercal "2023-05-05T19:58:01+07:00"

    Day: 2R (17 of 30)
    Month: VĬSAKH
    Years: 2567 B.E, 1384 J.E, 2023 C.E
    Days: 384 days
    Zodiac: THOS
    Sequence: V បញ្ចស័ក
